CONTIKI = ../../../..

TARGET = u101

CC=arm-none-eabi-gcc
AR=arm-none-eabi-ar
OBJCOPY=arm-none-eabi-objcopy

CONTIKI_TARGET_MAIN=contiki-u101-stm32f-main.c
PROJECT_SOURCEFILES = lmp.c

all: lmptest


include $(CONTIKI)/Makefile.include
