CONTIKI = ../../../..

TARGET = u101-stm32f

CC=arm-none-eabi-gcc
AR=arm-none-eabi-ar
OBJCOPY=arm-none-eabi-objcopy

CONTIKI_TARGET_MAIN=contiki-u101-stm32f-main.c

all: coulombtest


include $(CONTIKI)/Makefile.include
