CONTIKI = ../../..

TARGET = u101-stm32l

CC=arm-none-eabi-gcc
AR=arm-none-eabi-ar
OBJCOPY=arm-none-eabi-objcopy

CONTIKI_TARGET_MAIN=../../contiki-u101-stm32l-main.c

all: rtctest.bin


include $(CONTIKI)/Makefile.include
