CONTIKI = ../../../..

TARGET = u101

CC=arm-none-eabi-gcc
AR=arm-none-eabi-ar
OBJCOPY=arm-none-eabi-objcopy

CONTIKI_TARGET_MAIN=contiki-main.c

all: rtctest.bin


include $(CONTIKI)/Makefile.include
